# Generated by Django 2.0 on 2020-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oschina',
            name='title',
            field=models.TextField(max_length=500, null=True, verbose_name='标题'),
        ),
    ]
