# Generated by Django 2.0 on 2020-03-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_auto_20200328_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oschina',
            options={'ordering': ['id']},
        ),
    ]
